### ISSUE TITLE
New request: Css zim request

### ISSUE THREAD

**Issue by Cybertextaak** [openzim/zim-requests#1183]
- Website URL: https://developer.mozilla.org/en-US/docs/Web/CSS
- License: Creative Commons | Public domain or any available
- Desired ZIM Title: MDN Web Docs_Web
CSS
- Desired ZIM Description: Anything as per it.
- Desired ZIM Logo: https://developer.mozilla.org/en-US/
- Language (ISO 639-3): English
- Is this a MediaWiki?: No

If it gets available faster, God blesses our learnings. Thank you! For making available this healing facility.

**Comment by Popolechien** [comment]
we already have https://farm.openzim.org/recipes/developer.mozilla.org_en but I see it is set to dev. It looks like the last iteration succeeded but that was 4 months ago and I suspect the file went away with the September Purge and a bug has been filed as per https://github.com/openzim/zim-requests/issues/1044

Since the recipe exists and is on our radar I'll close this as duplicate.
