### ISSUE TITLE
Remove too small TED ZIMs

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1226]
### ZIM(s) location

https://library.kiwix.org/viewer#ted_mul_artificial-intelligence
https://library.kiwix.org/viewer#ted_mul_ai

### Recipe(s) URL

https://farm.openzim.org/recipes/ted_topic_ai
https://farm.openzim.org/recipes/ted_topic_artificial-intelligence

### Readers tested

- [ ] Kiwix-serve on iOS (iPad / iPhone)
- [ ] Kiwix-serve on Android (phone or tablet)
- [x] Kiwix-serve on Windows
- [ ] Kiwix-serve on Linux
- [ ] Kiwix-serve on Raspberry Pi (e.g. hotspot)
- [ ] Kiwix-serve on Mac
- [ ] pwa.kiwix.org
- [ ] Kiwix JS - Chrome extension
- [ ] Kiwix JS - Firefox extension
- [ ] Kiwix JS - Edge extension
- [ ] Kiwix for Android application
- [ ] Kiwix for MacOS application
- [ ] Kiwix for iOS (iPad/iPhone) application

### Which ZIM versions are impacted?

All PROD versions are impacted

### Details

If I select the AI category on TED I get 233 videos (2.3 GB), whereas the Artificial Intelligence file only has 3 (29GB).

Only one video from the Artificial Intelligence zim is not found in the AI one, so at this stage the question is more whether this is our problem or TED's.

**Comment by benoit74** [comment]
I propose that we delete all ZIMs (and corresponding Zimfarm recipes) which have fewer than a given amount of videos. 

I don't know exactly where the threshold should be, but definitely a ZIM with only 3 videos is not worth it.

This is more TED problem (it looks like they create tags "on-the-fly" and do not retag all existing videos once a new tag is created) but then it is then becoming our problem.

I suggest we start with a threshold at 5, meaning we will delete following recipes (some have not even already achieved to create a ZIM, because the number of video online does not mean that we will achieve to grab all videos, we might have issues to grab few of them):
- ted_topic_black-history
- ted_topic_black-history-month
- ted_topic_collective
- ted_topic_competition
- ted_topic_crowdsourcing
- ted_topic_geography
- ted_topic_hinduism
- ted_topic_humanities
- ted_topic_infectious-generosity
- ted_topic_judaism
- ted_topic_podcast
- ted_topic_reproductive-health
- ted_topic_soccer
- ted_topic_tv
- ted_topic_veganism

<details><summary>Click arrow to get the whole list of topics with number of videos:</summary>
<p>
<code>{
  "science": 1590,
  "ted conference": 1566,
  "technology": 1509,
  "ted-ed": 1191,
  "education": 1136,
  "animation": 1102,
  "social change": 1015,
  "culture": 943,
  "business": 837,
  "tedx": 821,
  "society": 790,
  "health": 768,
  "history": 753,
  "global issues": 733,
  "design": 667,
  "innovation": 601,
  "humanity": 590,
  "climate change": 573,
  "personal growth": 557,
  "biology": 549,
  "art": 533,
  "communication": 528,
  "future": 517,
  "community": 497,
  "environment": 497,
  "creativity": 468,
  "entertainment": 432,
  "sustainability": 430,
  "activism": 415,
  "psychology": 399,
  "work": 397,
  "brain": 377,
  "medicine": 368,
  "nature": 357,
  "health care": 352,
  "politics": 352,
  "music": 340,
  "performance": 340,
  "economics": 335,
  "animals": 323,
  "human body": 320,
  "collaboration": 305,
  "leadership": 301,
  "ted fellows": 301,
  "storytelling": 300,
  "women": 292,
  "government": 286,
  "identity": 268,
  "invention": 264,
  "kids": 262,
  "engineering": 261,
  "computers": 258,
  "medical research": 257,
  "countdown": 256,
  "equality": 250,
  "africa": 239,
  "public health": 236,
  "ai": 235,
  "internet": 228,
  "data": 226,
  "war": 225,
  "food": 223,
  "united states": 218,
  "disease": 217,
  "mental health": 206,
  "space": 204,
  "relationships": 198,
  "cities": 197,
  "math": 193,
  "emotions": 190,
  "ocean": 185,
  "race": 185,
  "evolution": 182,
  "family": 171,
  "gender": 166,
  "policy": 166,
  "writing": 166,
  "physics": 165,
  "neuroscience": 163,
  "democracy": 159,
  "energy": 156,
  "self": 151,
  "exploration": 149,
  "language": 148,
  "money": 146,
  "illness": 145,
  "architecture": 144,
  "entrepreneur": 142,
  "happiness": 142,
  "humor": 142,
  "universe": 142,
  "media": 138,
  "motivation": 136,
  "photography": 136,
  "religion": 135,
  "decision-making": 132,
  "violence": 130,
  "journalism": 125,
  "law": 125,
  "parenting": 125,
  "philosophy": 125,
  "work-life balance": 123,
  "ancient world": 122,
  "finance": 122,
  "literature": 122,
  "love": 122,
  "pollution": 120,
  "social media": 120,
  "teaching": 118,
  "film": 117,
  "biodiversity": 116,
  "poetry": 114,
  "potential": 113,
  "software": 112,
  "agriculture": 108,
  "machine learning": 108,
  "books": 106,
  "visualizations": 106,
  "beauty": 104,
  "death": 103,
  "robots": 103,
  "genetics": 101,
  "international development": 101,
  "biotech": 99,
  "poverty": 98,
  "success": 94,
  "water": 94,
  "astronomy": 91,
  "sports": 88,
  "youth": 88,
  "infrastructure": 87,
  "cancer": 86,
  "transportation": 85,
  "insects": 84,
  "dna": 82,
  "ecology": 81,
  "cognitive science": 80,
  "sex": 80,
  "pandemic": 79,
  "conservation": 78,
  "memory": 78,
  "empathy": 76,
  "goals": 76,
  "renewable energy": 76,
  "comedy": 75,
  "compassion": 75,
  "crime": 75,
  "india": 75,
  "algorithm": 74,
  "justice system": 74,
  "anthropology": 73,
  "coronavirus": 73,
  "farming": 73,
  "ethics": 72,
  "fish": 72,
  "investing": 72,
  "aging": 70,
  "product design": 69,
  "middle east": 68,
  "urban planning": 68,
  "chemistry": 67,
  "natural resources": 67,
  "electricity": 66,
  "planets": 65,
  "women in business": 65,
  "disability": 64,
  "feminism": 64,
  "immigration": 64,
  "demo": 63,
  "indigenous peoples": 62,
  "virus": 62,
  "code": 61,
  "depression": 61,
  "plants": 61,
  "consciousness": 59,
  "marine biology": 59,
  "china": 58,
  "dance": 57,
  "lgbtqia+": 57,
  "natural disaster": 57,
  "refugees": 56,
  "vaccines": 56,
  "microbiology": 55,
  "gaming": 53,
  "fear": 52,
  "inclusion": 52,
  "personality": 52,
  "statistics": 52,
  "corruption": 50,
  "diversity": 50,
  "human rights": 50,
  "philanthropy": 50,
  "prison": 50,
  "drugs": 49,
  "audacious project": 48,
  "bacteria": 48,
  "curiosity": 48,
  "marketing": 48,
  "sleep": 47,
  "asia": 46,
  "best of the web": 46,
  "fashion": 46,
  "capitalism": 45,
  "sociology": 44,
  "tedmed": 44,
  "trees": 44,
  "ted en espa\xc3\xb1ol": 43,
  "consumerism": 42,
  "ted membership": 42,
  "terrorism": 42,
  "discovery": 41,
  "solar system": 41,
  "online privacy": 40,
  "productivity": 40,
  "time": 40,
  "sound": 39,
  "weather": 39,
  "anthropocene": 38,
  "sight": 37,
  "flight": 36,
  "industrial design": 36,
  "solar energy": 36,
  "theater": 36,
  "ux design": 36,
  "behavioral economics": 35,
  "magic": 35,
  "public space": 35,
  "travel": 35,
  "bioethics": 34,
  "slavery": 34,
  "trust": 34,
  "military": 32,
  "mindfulness": 32,
  "ted prize": 32,
  "resources": 31,
  "archaeology": 30,
  "europe": 30,
  "life": 30,
  "manufacturing": 30,
  "maps": 30,
  "painting": 30,
  "sexual violence": 30,
  "spoken word": 30,
  "surveillance": 30,
  "friendship": 29,
  "illusion": 29,
  "ted residency": 29,
  "aids": 28,
  "fossil fuels": 28,
  "heart": 28,
  "south america": 28,
  "transgender": 28,
  "aliens": 27,
  "biosphere": 27,
  "birds": 27,
  "surgery": 27,
  "biomimicry": 26,
  "medical imaging": 26,
  "big bang": 25,
  "gardening": 25,
  "nanotechnology": 25,
  "plastic": 25,
  "protest": 25,
  "telescopes": 25,
  "virtual reality": 25,
  "drones": 24,
  "encryption": 24,
  "library": 24,
  "mars": 24,
  "worklife": 24,
  "addiction": 23,
  "egypt": 23,
  "pregnancy": 23,
  "quantum": 23,
  "synthetic biology": 23,
  "mission blue": 22,
  "paleontology": 22,
  "dark matter": 21,
  "interview": 21,
  "museums": 21,
  "alzheimer\'s": 20,
  "botany": 20,
  "cyber security": 20,
  "geology": 20,
  "international relations": 20,
  "primates": 20,
  "prosthetics": 20,
  "blindness": 19,
  "dinosaurs": 19,
  "fungi": 19,
  "vulnerability": 19,
  "astrobiology": 18,
  "exercise": 18,
  "hearing": 18,
  "ptsd": 18,
  "public speaking": 18,
  "shopping": 18,
  "smell": 18,
  "ted books": 18,
  "nuclear energy": 17,
  "television": 17,
  "autism spectrum disorder": 16,
  "bees": 16,
  "blockchain": 16,
  "driverless cars": 16,
  "neurology": 16,
  "ted connects": 16,
  "toys": 16,
  "wind energy": 16,
  "antarctica": 15,
  "metaverse": 15,
  "rivers": 15,
  "science fiction": 15,
  "3d printing": 14,
  "body language": 14,
  "ebola": 14,
  "islam": 14,
  "meditation": 14,
  "moon": 14,
  "suicide": 14,
  "brazil": 13,
  "crispr": 13,
  "sun": 13,
  "christianity": 12,
  "coral reefs": 12,
  "glaciers": 12,
  "nasa": 12,
  "rocket science": 12,
  "augmented reality": 11,
  "graphic design": 11,
  "buddhism": 10,
  "bullying": 10,
  "string theory": 10,
  "asteroid": 9,
  "cryptocurrency": 9,
  "grammar": 9,
  "pain": 9,
  "tech": 9,
  "deextinction": 8,
  "homelessness": 8,
  "microbes": 8,
  "nfts": 8,
  "bionics": 7,
  "conducting": 7,
  "ideas": 7,
  "typography": 7,
  "forensics": 6,
  "artificial intelligence": 5,
  "atheism": 5,
  "street art": 5,
  "wildlife": 5,
  "black history month": 3,
  "humanities": 3,
  "judaism": 3,
  "collective": 2,
  "competition": 2,
  "reproductive health": 2,
  "tv": 2,
  "veganism": 2,
  "black history": 1,
  "career": 1,
  "crowdsourcing": 1,
  "geography": 1,
  "growing up": 1,
  "hinduism": 1,
  "infectious generosity": 1,
  "podcast": 1,
  "soccer": 1,
  "spirituality": 1
}</code>
</p>
</details> 

Or maybe our strategy to create ZIM per topic is too fragile (sorry to come back to this, but I still consider we are not really doing our publisher job very seriously on this topic ... but neither does TED so ...)

WDYT?

**Comment by Popolechien** [comment]
Makes sense to me.

**Comment by benoit74** [comment]
All ZIMs mentioned above have been marked for removal from the library, should be done within next hour.

All corresponding recipes have been deleted from Zimfarm.

Keeping issue open until I've confirmed that files are gone from the library and I've removed files from storage.

**Comment by benoit74** [comment]
I forgot to also delete `ted_topic_artificial-intelligence` which is the root cause of this issue ... (limit of 5 is applied on number of expected videos, not on number of videos we really achieve to download and push to the ZIM)

**Comment by benoit74** [comment]
All files removed from library and from download.kiwix.org
