### ISSUE TITLE
Simplify Wikipedia ZIM file offering

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#129]
Wikipedia is big and successful and we can "offline" it with many options. As a result:
* We can not deal with all the option combinations, so we need to make choices
* We use to concatenate all the options to define a content which might be complicated
* The one the user need is often the one missing and we have no clear explanation why we do a combination of options more than an other.
* The lifecycle mgmt of the ZIM files will become complicated if we "randomly" create new ZIM files of Wikipedia with new combination of options

For all these reasons and a few others, we need to agree on what we do and how we call it. Anything won't be offer as standard in the the book portfolio of Kiwix.

**Comment by kelson42** [comment]
WIP

* XXS = TOP50K
* XS    = no multimedia files, TOP500K
* S      = no multimedia files, TOP1M
* M      = no multimedia files, all
* L       = with pictures, TOP500K
* XL     = with pictures, TOP1M
* XL     = with pictures+vid, TOP
* XXL   =
* XXL   =
* XXXL =
* XXXL = 
* XXXL = _everything = no `mwoffliner` filtering options_

**Comment by kelson42** [comment]
* mini (nodet) + 50K = `50k_mini`
* nopic + 50K = `50k_nopic`
* maxi (novid) + 50K = `50k_maxi`
* 50K = `50k`
* mini (nodet) + ALL = `all_mini`
* nopic + ALL = `all_nopic`
* maxi (novid) + ALL = `all_maxi`
* ALL = `all`

**Comment by Popolechien** [comment]
Yes we should have two dimensions:
Content size: Mini (curr. nodet); NoPic; Maxi (curr. NoVid); Super (the complete wiki with videos, not publically available)
Selection size: Top (e.g. Top 50k articles) or All (e.g. all 5m articles on enwp)

We end up with 6 possible selections: 
MiniTop / MiniAll
NoPicTop / NoPicAll
MaxiTop / MaxiAll

And keep SuperTop/SuperAll for partnerships that can afford the storage space.

**Comment by amirh123123** [comment]
and creat novid nodet no video and sounds and creat nodet with all pictures videos and sounds

**Comment by kelson42** [comment]
@Popolechien I think we are ready to implement that in the ZIM farm. I think around 60 Wikipedias are concerned (+100.000) articles. Now the question to do is: what is the title, description, logo for all these selection? in local language?

**Comment by Popolechien** [comment]
Are you asking about the name, logo and description as they appear in the downloader and libraries? I think that for the time being we can leave the names as is with the regular Wikipedia logo (because that's what it is and we won't have a designer before October). Fundamentally these only replace novid / nopic / nodet with something (hopefully) a little more explicit, so it would make sense to call them 
``Mini`` Wikipedia_native_name
``NoPic``
``Maxi``

For instance in Bulgarian we'd have ``Mini Уикипедия``
The description text could be worked out indeed as I realize that currently what's available in near-useless (e.g. "Wikipedia, from Wikipedia"). For the time being we could blanket replace it with ``Top 50k articles`` or ``Full content`` (for ``Top`` and ``all``) as shown below:
![mini top](https://user-images.githubusercontent.com/21675885/57384398-d4ce8d80-71b0-11e9-991d-cb6c45e1ccb8.jpg)

It's in English but we will eventually get it translated if we can export the list of languages.

**Comment by rgaudin** [comment]
I am generating those using the Logo and sitename from the API and using an auto translation of `A selection of the best {nb} Wikipedia articles in {lang_name}` as description. I'll add `Mini ` to the title.

We'll have to rename the articles list files on the server to have a nice name. Currently, it's gonna be `wikipedia_ar_50000_nopic-2019-05.zim`.

By moving `tops/50000` to `tops/50000/top` we would get `wikipedia_ar_top_nopic-2019-05.zim`.

I can set it to have the `mini` part in the name by passing the full prefix.

**Comment by rgaudin** [comment]
Done via the creation of 372 schedules (62 x 6).
We'll need to update `mwoffliner` to support more flexible file names and reduce those schedules by 3.

**Comment by tim-moody** [comment]
I think this loses information because nodet, nopic, novid tell you why something is smaller or bigger, but mini, medi, maxi only talk about size. BUT I gave up trying to parse the names at the last change. For me at least I hope that the tags do not change as I display them to users to show the kinds of media included. Also, please do not change the naming convention that has the name ending in _YYYY-MM.zim as I use that pattern to separate the generic name from the version.

**Comment by kelson42** [comment]
@tim-moody Filename structure won't change, but tags will change, here is the plan so far https://github.com/kiwix/kiwix-lib/issues/131#issuecomment-384685377

**Comment by tim-moody** [comment]
@kelson42 if I read this correctly you are moving to tags such as has_videos instead of not no_vids. That sounds great and something I have lobbied for. Not sure what the timeline is as there have been no contributions to the issue for over a year.

**Comment by metal450** [comment]
Is there documentation anywhere on what "maxi" actually means?  Does this refer to the image compression of the images, or something else...?

**Comment by metal450** [comment]
Awesome, thanks :)
