### ISSUE TITLE
Request: Create a ZIM for conservapedia.com

### ISSUE THREAD

**Issue by okkebal** [openzim/zim-requests#134]
I noticed there are two left-wing wiki's on Kiwix, namely RationalWiki and Psiram. How about also adding some wikis from a more right-wing perspective? Although these sites proclaim to be neutral I would dare you to find a Rational Wiki article about a right-wing person that has no name calling in it. Just yelling someone is an idiot/oaf/doom-sayer etc does not help at all and is not very "rational".

I would like to suggest adding Convervapedia. 
https://www.conservapedia.com/

**Comment by kelson42** [comment]
From the licensing point of view, we have here IMO an interesting case. See https://www.conservapedia.com/Conservapedia:Copyright. Conservopedia seems to violate the author's rights by not attributing their content to their respective authors. By reproducing that, we would do so ourself ; this would be a problem of course. On the top of that, it seems to be - because of that lack of attribution - almost no visibility and real possibility to verify the copyright status of many of the content/pictures.

@Popolechien Any thoughts about this specific licensing point?

**Comment by okkebal** [comment]
"By reproducing that, we would do so ourself ; this would be a problem of course. " 

Why? The authors seem to have waived this "attribution" right by joining the conservapedia site. Why is this a problem for us?

I have much more problems with the blatant lies and disinformation and slander thats on rationalwiki. I guess that no problem us? Kiwix is hosting these clear cases of libel.  According to Rational Wiki Alex Jones is "batshit crazy". Why do you host this??? Tell me!

**Comment by kelson42** [comment]
@okkebal We have understood that you disagree with what is written in Rationalwiki. We are not going to run any editorial discussion here because this place is about technical and legal challenges.

**Comment by Popolechien** [comment]
@Kelson - yeah they admit using other people's images (I guess it's fair use in the US but that does not work in Europe or most civil law jurisdictions).

Also, if not more problematic is "_For historical reasons a few entries are compelled to impose greater restrictions on reuse as noted_" at the bottom - those do not seem to be tagged, so there's no way for a scrapper to figure that one out easily. I'm sure everything could be sorted, ultimately, but it's not our job and we don't have the resources right now.

**Comment by kelson42** [comment]
Content licence does not allow to redistribute it.
