### ISSUE TITLE
Make a ZIM of https://hitchwiki.org

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#178]

**Comment by kelson42** [comment]
Done https://farm.openzim.org/recipes/hitchwiki/

**Comment by guaka** [comment]
<img width="926" height="731" alt="Image" src="https://github.com/user-attachments/assets/8d06f940-7bfe-478c-8681-bb7ee325b589" />

I can help!

**Comment by Popolechien** [comment]
ZIM file available at https://dumps.hitchwiki.org/zim/

**Comment by kelson42** [comment]
I don't understand.... people at hitchwiki manage to do it and we don't! Where is the problem?

**Comment by Popolechien** [comment]
See https://github.com/openzim/zim-requests/issues/633#issuecomment-4922815762

Same website owner - Cloudflare block.

**Comment by kelson42** [comment]
@guaka Are our servers whitelisted in your cloudfare config?

**Comment by guaka** [comment]
ZIMs available at https://dumps.hitchwiki.org/zim/ - no CF on dumps subdomain anymore

can also try to whitelist kiwix servers for hitchwiki.org if you have IP addresses for me?

**Comment by kelson42** [comment]
@benoit74 Do we have a reference location for these IPs? Maybe even a solution where the list could be dynamically loaded into Cloufare?

**Comment by benoit74** [comment]
> Do we have a reference location for these IPs? 

Nope, especially because some of these are private and I'm not sure even ours are not something to keep restricted.

> Maybe even a solution where the list could be dynamically loaded into Cloufare?

This is only some of the work to do, see https://github.com/kiwix/operations/issues/373 (we also need to ensure our scraper respect the robots.txt, ...). 

And on this specific issue of hitchwiki.org, I don't see where building the ZIM on our own is aligned with our strategy to allow more people to build ZIMs for us. We have a very capable person which build a good ZIM, we should follow our strategy and let him upload the ZIM on our CMS directly (spoiler, it's coming very soon).
