### ISSUE TITLE
Existing ZIM: 

### ISSUE THREAD

**Issue by tim-moody** [openzim/zim-requests#224]
I do not find newly named equivalents for the following:
* wikihow_en_2016-11.zim
* wikipedia_bollywood_en
* bouquineux_fr_all_2013-07.zim
* cest-pas-sorcier_fr_all_2018-06.zim
* crashcourse_en_all_2018-06.zim
* oer4schools_en_all_2015-11.zim
* wikistage_fr_all_2018-06.zim

**Comment by kelson42** [comment]
> * wikihow_en_2016-11.zim

This was the ZIM version of an HTML dump made by Rachel. If there is a new one, happy to make a new ZIM. Otherwise we will need to make our own scraper like planned for years already. See https://github.com/openzim/wikihow

> * wikipedia_bollywood_en

New versions are available, but the file naming has changed a bit. See https://farm.openzim.org/recipes/wikipedia_en_bollywood

> * bouquineux_fr_all_2013-07.zim

No new version, was a one shot.

> * cest-pas-sorcier_fr_all_2018-06.zim

We will make a new one. It’s in the pipe. https://farm.openzim.org/recipes/cest-pas-sorcier_fr_all

> * crashcourse_en_all_2018-06.zim

Same. See https://farm.openzim.org/recipes/crashcourse_en_all

> * oer4schools_en_all_2015-11.zim

I should try to make a new one.

> * wikistage_fr_all_2018-06.zim

Same, a new one is in the pipe.

**Comment by kelson42** [comment]
Done:
* <s>cest-pas-sorcier_fr_all_2018-06.zim</s>
* <s>crashcourse_en_all_2018-06.zim</s>
* <s>wikistage_fr_all_2018-06.zim</s>

Let:
* oer4schools_en_all_2015-11.zim

**Comment by kelson42** [comment]
I don't think this is any value to make a new ZIM file of oer4schools as the web site does not evolve.
