### ISSUE TITLE
New ZIM: Low-tech Lab

### ISSUE THREAD

**Issue by LowtechLab** [openzim/zim-requests#270]
- Website URL: https://wiki.lowtechlab.org/wiki/Explore
- License: Creative Commons 
- Desired ZIM Title: Low-tech Lab
- Desired ZIM Description: Low-tech Lab's tutorials allow building low-tech system. These tools are accessible, sustainable and respond to basic needs such as accomodation, agriculture or energy.
- Desired ZIM Icon –png (URL or attach one): 
![image](https://user-images.githubusercontent.com/66359936/83634010-2018c280-a5a2-11ea-9aea-f2f83d89ec45.png)

- Language (ISO 639-3): **eng**
- Desired Main Page (homepage): https://lowtechlab.org/
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/lowtechlab_en

We'll see in a couple of days when the zim is published what it looks like.

**Comment by kelson42** [comment]
@LowtechLab Unfortunately for the moment, we can not scrape properly the content (at least) because a problem on your backend. Your `visualeditor` API backend returns partly HTML encoded content which then is not interpreted properly by our scraper.

For example, at https://wiki.lowtechlab.org/w/api.php?action=visualeditor&mobileformat=html&format=json&paction=parse&page=Compost_Bokashi_de_cuisine, we get the JSON with this kind of HTML: `<span class=\"tuto-details-author-box\">&lt;a class='avatar-image' href='/wiki/Utilisateur:Low-tech_Lab'>&lt;img src='/images/avatars/dkf_Low_tech_Lab_8_ml.png?r=1516034750' alt='avatar' border='0' />&lt;/a>&lt;a class='name' href='/wiki/Utilisateur:Low-tech_Lab'><span class=\"tuto-details-author-name\">Low-tech Lab</span>&lt;/a></span>`

You can see that the characters `<` is partly replaced by its HTML entity, partly not and its `>` counterpart is always OK.

Than way the HTML can not render properly.

@LowtechLab Would you be able to fix the problem?

**Comment by kelson42** [comment]
I have deleted the broken ZIM files from our repository and disabled the Zimfarm recipe for the time being.

**Comment by kelson42** [comment]
The problem of bad links encoding is tracked here https://github.com/openzim/mwoffliner/issues/1360. Closing to avoid duplicates
