### ISSUE TITLE
community.spiceworks.com

### ISSUE THREAD

**Issue by IronArni** [openzim/zim-requests#332]
- Website URL: https://community.spiceworks.com/
- License: Public domain
- Desired ZIM Title: community.spiceworks.com
- Desired ZIM Description: IT Questions & Answers from spiceworks.com community 
- Desired ZIM Icon –png (URL or attach one): https://3upg5n1ajpdonqkkp34tcif1-wpengine.netdna-ssl.com/brand/wp-content/themes/styleguide/assets/images/logo-examples/horizontal-full_color.png
- Language (ISO 639-3): eng
- Desired Main Page (homepage, if different from website URL): n/a
- Is this a MediaWiki?: no

**Comment by Popolechien** [comment]
> License: Public domain

I see © Copyright 2006 - 2021 Spiceworks Inc., as well as the following statement "''Except as otherwise set forth herein, the Service is made available to you for: (a) your personal use; (b) your internal business use; or (c) if you are a Managed Service Provider (“MSP“), or Value Added Reseller (“VAR”), use in connection with the commercial support of your customers, in compliance with all applicable laws, rules, and regulations. If you want to make any other commercial use of the Service, including but not limited to selling, distributing, or providing access to the Service for payment, you must enter into a separate written agreement with Spiceworks or obtain Spiceworks’ written permission in advance.'' (..)
''You may not use any “deep-link”, “page-scrape”, “robot”, “spider”, or other automatic device, program, algorithm, or methodology, or any similar or equivalent manual process, to access, acquire, copy, or monitor any portion of the Service''"

We're not making a commercial use of the service but I'd be cautious nevertheless. @IronArni have you tried scraping a private copy via www.youzim.it ?

**Comment by IronArni** [comment]
Hello! Yes, I tried to do this through www.youzim.it several times. Every
time I had an error during these requests.


пн, 15 мар. 2021 г. в 12:49, Popo le Chien ***@***.***>:

**Comment by Popolechien** [comment]
Can you please open a ticket on [zimit/issues](../../zimit/issues) and describe what the problem was?

**Comment by Popolechien** [comment]
closing this specific ticket for now.
