### ISSUE TITLE
New ZIM request: CText

### ISSUE THREAD

**Issue by ZhuningS** [openzim/zim-requests#347]
*Please use the following format for a ZIM creation request (and delete unnecessary information*

- Website URL: https://ctext.org/
- License: Public domain
- Desired ZIM Title: Chinese Text Project
- Desired ZIM Description: The Chinese Text Project is an online open-access digital library that makes pre-modern Chinese texts available to readers and researchers all around the world. The site attempts to make use of the digital medium to explore new ways of interacting with these texts that are not possible in print. With over thirty thousand titles and more than five billion characters, the Chinese Text Project is also the largest database of pre-modern Chinese texts in existence.
- Desired ZIM Icon –png (URL or attach one): https://ctext.org/static/apple-touch-icon.png
- Language (ISO 639-3): zh (zh_cn OR zh_tw)
- Desired Main Page (homepage, if different from website URL): https://ctext.org/zh
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
"Site design and content copyright 2006-2021. (..) Please note that the use of automatic download software on this site is strictly prohibited, and that users of such software are automatically banned without warning to save bandwidth."

@ZhuningS Would you be able to put us in touch with the site's operator in order to grant permission? they can contact us via contact at kiwix dot org.

Until this is cleared I will have to close the ticket unfortunately.
