### ISSUE TITLE
Lurkmore.to

### ISSUE THREAD

**Issue by jurok04** [openzim/zim-requests#413]
- Website URL: https://lurkmore.to/
- License: CC BY 3.0
- Desired ZIM Title: lurkmore.to_2022
- Desired ZIM Description: lurkmore.to full dump 2022
- Desired ZIM Icon –png (URL or attach one): http://lurkmore.to/skins/common/images/Lurklogo-small-censored.png
- Language (ISO 639-3): rus
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment]
@jurok04 Seeing that the website is in Russian could please write something more descriptive in that language (instead of "full dump")? Can you confirm that this would be grammatically correct?
` Пародийная энциклопедия современной культуры, фольклора и субкультур, и всего остального.`

**Comment by jurok04** [comment]
Thank you! Yes, this description is perfectly  grammatically correct.

**Comment by Popolechien** [comment]
Ah! Turns out we had already created [a recipe](https://farm.openzim.org/recipes/lurkmore_ru) last year, and that it failed for the following reason:
`Mediawiki version 1.19.24 not supported should be >=1.27` (it failed again minutes ago for the same reason)

Won't work until the Lurkmore folks update their wiki, so I suggest you drop them a line pointing to this ticket to let them know.

**Comment by jurok04** [comment]
It is very, very unfortunate that this cannot be done. The site owners decided to mothball the project, no update is expected. Can you advise how else to get a dump of this site in zim?

**Comment by Popolechien** [comment]
@jurok04 Unfortunately, there is not much we can do. Maybe try [zimit](https://youzim.it)? Be mindful that you'll need Kiwix-serve to make it work then.
