### ISSUE TITLE
New ZIM request: maitrelucas.fr

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-requests#469]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://maitrelucas.fr/
- License: **Limited-distribution only (sponsored, private)**
- Desired ZIM Title: **Maître Lucas : <topic>**
- Desired ZIM Description: _see below_
- Desired ZIM Icon –png (URL or attach one): https://drive.farm.openzim.org/maitrelucas/Maitre-Lucas-square.png
- Language (ISO 639-3): **fra**

---

Awaiting a list of agreed-upon videos and PDFs URLs

**Comment by Popolechien** [comment]
Here is the directory for content: https://drive.farm.openzim.org/_admin/#/maitrelucas
(I've put the logos already)
Now for the content: there is a bunch of folders [here](https://drive.google.com/drive/folders/1IXu_II3-4VL9x6QaEN3wM3fyg8OwL6wg?usp=sharing) that have been sorted by topic. Each folder that begins with `Maitre Lucas:` should yield one zim file (so 21 in total if I am not mistaken).

Some, like `Maître Lucas: Apprendre à dessiner" contain the files and a google sheet listing all necessary parameters to be exported in the JSON. I don't think we need to use the same file description over and over, but we certainly could use this text for the _zim_ description.
So for the specs above we would have:
- Desired ZIM Title: **Maître Lucas : Apprendre à dessiner**
- Desired ZIM Description: Fiches d'exercices
- Desired ZIM Icon –png (URL or attach one): https://drive.farm.openzim.org/maitrelucas/Maitre-Lucas-square.png (for the 48x48 icon)
- Desired ZIM Icon –png: https://drive.farm.openzim.org/maitrelucas/Maitre-Lucas-300x65px.png for the rectangular one


Now some folders may content subfolders because the partner initially thought there could be an arborescence (should be a couple only). I've tasked @siemsie with aggregating the google sheets.
