### ISSUE TITLE
Creating a Zim file for futurecoder.io

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#588]
Could you please create the zim file for Future coder, the information are mentioned below?

Website URL: https://futurecoder.io/
License: Open source
Desired ZIM Title: futurecoder.io
Desired ZIM Description: Future Coder to learn Python Language from scratch.
Desired ZIM Icon –png (URL or attach one): ![terminal](https://user-images.githubusercontent.com/116940574/228087267-6bd9edb6-fa30-4a0e-9378-8b0df91fd020.png)
Language (ISO 639-3): eng
Is this a MediaWiki?: no

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/futurecoder.io_en_all
I'll update the library link once ready

**Comment by RavanJAltaie** [comment]
https://dev.library.kiwix.org/viewer#futurecoder.io_en_all_2024-09
The coding part is fine, but the learning part is not opening. @benoit74 can you check please?
Shall we fix this then make different zims for the other languages available?

**Comment by benoit74** [comment]
Unfortunately this site can probably not be scrapped by zimit, it is just issuing to much dynamic calls (which is logic since its purpose is to be interactive) to the server which cannot be archived in a ZIM

The coding part is not working at all, it displays a first UI but then nothing works.

I propose to close this issue as "infeasible".

**Comment by Popolechien** [comment]
Okie dokie. Is this like FreeCodeCamp that at some point we could get it, but only with a dedicated scraper?

**Comment by benoit74** [comment]
Nope, this is is really not feasible, not even with a dedicated scraper, it is way for more interactive than freecodecamp.
