### ISSUE TITLE
Make a zim of Hackteria

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#6]
_From @Popolechien on September 4, 2018 5:59_

Address is http://hackteria.org/ and the wiki is under CC-by license.

_Copied from original issue: openzim/mwoffliner#372_

**Comment by kelson42** [comment]
@Popolechien Does not look to be a Mediawiki!?

**Comment by RavanJAltaie** [comment]
Requested
https://farm.openzim.org/recipes/hackteria.org

**Comment by RavanJAltaie** [comment]
Succeeded.

**Comment by benoit74** [comment]
ZIM still not published + not working in DEV.

I tried to fix the recipe and requested again (was using conflicting custom scope). I excluded the wiki since it is a mediawiki and this is not going to operate well on zimit. 

Should we add a ZIM request for the wiki itself (at http://hackteria.org/wiki) which could be scraped with mwoffliner?

**Comment by Popolechien** [comment]
MWOffliner probably won't pick it up but I would still give it a shot, yes. @RavanJAltaie can you please create a recipe just for that part?

**Comment by benoit74** [comment]
@Popolechien you should open a dedicated issue for the mwoffliner part, otherwise we will get lost between the two recipes / ZIMs.

**Comment by benoit74** [comment]
ZIM is mostly working but many images are broken because resolution is adapted depending on user-agent / screen size / ... 

Probably needs custom fuzzy rule, tagging this as upstream
