### ISSUE TITLE
Maitre Lucas

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#627]
Files are all in drive https://drive.farm.openzim.org/_admin/#/maitrelucas

**For all files:**
Language: fra
Banner: https://drive.farm.openzim.org/maitrelucas/Maitre-Lucas-300x65px.png
Logo: https://drive.farm.openzim.org/maitrelucas/Maitre-Lucas-square.png
Description: Des videos et exercices ludiques afin d’approfondir les leçons du CP au CM2 

There are more than 50 folders / books to create. Each has its own excel sheet with the list of files and descriptors to export as JSON, but just in case a tabbed master sheet is also available at
https://drive.farm.openzim.org/maitrelucas/Maitre%20Lucas%20aggregated%20sheet.xlsx

The following folders have subfolders but should be treated as one book to create:
[Conjugaison](https://drive.farm.openzim.org/_admin/#/maitrelucas/Maitre%20Lucas_%20Conjugaison)
[Ecriture](https://drive.farm.openzim.org/_admin/#/maitrelucas/Maitre%20Lucas_%20Ecriture)
[Grammaire](https://drive.farm.openzim.org/_admin/#/maitrelucas/Maitre%20Lucas_%20Grammaire)
[Lecture](https://drive.farm.openzim.org/_admin/#/maitrelucas/Maitre%20Lucas_%20Lecture)
[Espace et géométrie](https://drive.farm.openzim.org/maitrelucas/Mai%CC%82tre%20Lucas_%20Espace%20et%20ge%CC%81ome%CC%81trie/)
[Grandeurs et mesures](https://drive.farm.openzim.org/maitrelucas/Mai%CC%82tre%20Lucas_%20Grandeurs%20et%20mesures/)
[La planète Terre et l'environnement](https://drive.farm.openzim.org/maitrelucas/Mai%CC%82tre%20Lucas_%20La%20plane%CC%80te%20Terre%20et%20l_environnement/)
[Matériaux, mouvement, énergie et objets techniques](https://drive.farm.openzim.org/maitrelucas/Mai%CC%82tre%20Lucas_%20Mate%CC%81riaux,%20mouvement,%20e%CC%81nergie%20et%20objets%20techniques/)
[Questionner l'espace et le temps](https://drive.farm.openzim.org/maitrelucas/Mai%CC%82tre%20Lucas_%20Questionner%20l_espace%20et%20le%20temps/)

@rgaudin What would you need @RavanJAltaie and I to do to make it easier for you to generate these?

**Comment by rgaudin** [comment]
This is terrible. Please write down the instructions you send to people preparing nautilus files on a Wiki page in nautilus repo (can be in French) so we have a chance to make it clear and precise.

I've uploaded the 53 JSON files and created 53 accompanying ZIP files in the drive. Let me know if you encounter any difficulty.

FYI, the following files were not included because of missing metadata:

- `comparer_les_nombres_jusqu_à_100.pdf`
- `Les_nombres_jusqu_à_20_corrigé.pdf`
- `Les_nombres_jusqu_à_20.pdf`
- `Décrire_un_animal_cp_-_préparer_un_exposé_cp_ce1_cycle_2_français_production_d_écrits.mp4`
- `Lecture_CP_-_son_m_-_GS_-_CP_-_Cycle_2.mp4`
- `le_son_A_lecture_CP_cycle_2_français.mp4`
- `Lecture_CP_-_son_f_-_GS_-_CP_-_Cycle_2_(1).mp4`
- `Lecture_CP_-_son_E_-_GS_-_CP_-_Cycle_2.mp4`
- `Lecture_CP_-_son_é_-_GS_-_CP_-_Cycle_2.mp4`
- `Lecture_CP_-_son_ch_-_GS_-_CP_-_Cycle_2.mp4`
- `Lecture_CP_-_son_L_-_GS_-_CP_-_Cycle_2.mp4`
- `Lecture_CP_-_son_S_-_GS_-_CP_-_Cycle_2.mp4`
- `Lecture_CP_-_son_Y_-_GS_-_CP_-_Cycle_2.mp4`
- `Lecture_CP_-_son_I_-_GS_-_CP_-_Cycle_2.mp4`
