### ISSUE TITLE
armypub CSS

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#695]
The zimit scraping of [ArmyPubs](https://dev.library.kiwix.org/#lang=eng&q=army%20publishing) was successful, however the landing page has a search box that could be hidden as it is not able to function correctly. Following earlier discussion, a bit of _ad _hoc__ CSS could help cover it up apparently?

Zimfarm recipe is [here](https://farm.openzim.org/recipes/armypubs_en_all).

**Comment by benoit74** [comment]
Quick to implement, will be pretty fragile, but will do the job at least.
```
section.usa-prose {display: none}
```
I will finish to work on it monday.

**Comment by benoit74** [comment]
CSS seems ok with current website, I've even made it more "resilient" with `section.grid-container.usa-prose.usa-section` instead of `section.usa-prose`. We are quite lucky on this one, because there isn't much info to apply custom CSS in the HTML, luckily there is a specific one for this search box ...

I've uploaded the CSS to Zimfarm drive (https://drive.farm.openzim.org/armypubs/custom.css) and configured the recipe appropriately.

![image](https://github.com/openzim/zim-requests/assets/7102089/5cb49bce-98c7-4e73-b299-bd6926252892)

I re-requested the recipe

**Comment by RavanJAltaie** [comment]
Thanks @benoit74 , may I know what to do with similar recipes?

**Comment by Popolechien** [comment]
@RavanJAltaie We will need to open a request every time as the css they create is custom-made. In a nutshell the process will be:
1. Create receipe and zim
2. If zim works and shows a Search bar somewhere (which won't work) then
3. Open zim-request just like this one asking to hide the Search bar.

**Comment by benoit74** [comment]
4. assign the zim-request to rgaudin and myself, otherwise it will takes time before we know you need us :)

**Comment by RavanJAltaie** [comment]
Noted, will apply this process on every similar case

**Comment by Popolechien** [comment]
Worked like a charm. Thanks!
https://library.kiwix.org/content/armypubs_en_all_2023-08/
