### ISSUE TITLE
Google fonts CSS (Hiding the search bar)

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#700]
The file of google fonts on /hidden/dev is showing a search box.
https://dev.library.kiwix.org/viewer#fonts.google_en_2023-08/A/fonts.google.com/

Could you please help in removing that?
The recipe:
https://farm.openzim.org/recipes/fonts.google_en
#687

**Comment by benoit74** [comment]
Did you tried to open the ZIM when offline? 

From my test, it looks like:
- the ZIM is not working at all when offline, looks like most resources are from `fonts.gstatic.com`, `www.gstatic.com` and `ssl.gstatic.com` (at least) and those domains have not been crawled
- the search bar from `fonts.google.com` is working when offline. I.e. if you load `fonts.google.com` on your browser, then shutdown the internet (e.g. Wifi / Ethernet cable / ...) and try to use the search box, it works. So probably no reason to remove this search box.

Could you confirm that we can hence close this ticket?

**Comment by benoit74** [comment]
@RavanJAltaie could you provide an update regarding my answer please?
@Popolechien did I missed something?

**Comment by Popolechien** [comment]
@benoit74 I think we need to be clearer about which search bars should or should not be hidden, because right here I'm a bit confused tbh.

Generally speaking, if half or more of the resources cannot be browser offline then the zim file is not really useful and should be deleted.

**Comment by benoit74** [comment]
I don't mind to explain, this is exactly why I was asking.

From my point of view, the reason which leads you to remove something from a ZIM web page (created by zimit) is based on the fact that it provides no value / is confusing / is not working at all once offline.

In the previous case (armypub ZIM), the search bar was not working at all once offline because it requested something from a web server. And it was very confusing because it was very visible in the home page. This is generally the case, but not always.

In the present situation (google fonts ZIM), the search bar seems (cannot be sure since lots of content is missing) to be working perfectly well once offline and very valuable to the exploration of the ZIM content, so I do not see a good reason to remove it (but I may miss something).

Regarding the fact that many resources cannot be browsed offline, you just have to fix the recipe to include domains mentioned in the crawling and this would probably ensure that most resources will be available in the ZIM.

**Comment by benoit74** [comment]
I consider this as done, do not hesitate to reopen the issue if something is needed.
