### ISSUE TITLE
Removing Khan Academy Youtube Video

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#768]
As per an action item for this [issue](https://github.com/openzim/zimfarm/issues/878)
Please remove the files of Khan Academy videos on Youtube (All files with Khan Academy name in the folder [Videos](https://download.kiwix.org/zim/videos/)) as we have the content already in Khan Academy files themselves.
Number of files are 1136, that's why it's better to delete them with a script.

**Comment by benoit74** [comment]
FYI, there are only 1022 ZIMs with a `khan-academy-` name in https://download.kiwix.org/zim/videos/

But since `khan` is written 1136 times in the page (some ZIMs have `khan` multiple times in their names like `khan-academy-videos_en_first-order-differential-equations-differential-equations-khan-academy_2021-07.zim`), I assume this is the source of confusion.

Since this is a significant volume to restore/rebuild (900G!) if we realize we still need them, for now I just moved all files to [zim/.hidden/khan_backup_2023_12/](https://mirror.download.kiwix.org/zim/.hidden/khan_backup_2023_12/) so that they are not listed anymore in library.kiwix.org. Library will update automatically soon.

I will delete them definitely in 30 days, once we can probably be sure we don't need them anymore.

**Comment by RavanJAltaie** [comment]
Please let us know once deleted, thanks in advance @benoit74

**Comment by kelson42** [comment]
@RavanJAltaie It's not visible anymore in the library and can be considered deleted. Closing the ticket,

**Comment by benoit74** [comment]
Sorry about that, I forgot to update the issue
