### ISSUE TITLE
Move `developer.mozilla.org_en_all_2024-01.zim` from the development server to library.kiwix.org / download.kiwix.org

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zim-requests#791]
I have checked this file `developer.mozilla.org_en_all_2024-01.zim` (which is a standard classic Zimit file, not Zimit 2.0), and it is the first good / correct scrape of MDN for a long time. As such, I think it should be moved to the zimit directory on download.kiwix.org / library.kiwix.org since the last good scrape there is from nearly a year ago (2023-02).

I have access to download.kiwix.org for uploading release packages, so I suppose I could upload it there myself (and happy to do so), but I'm not sure if other things are needed (like any metadata for library.kiwix.org). @kelson42 ?

**Comment by rgaudin** [comment]
Just mention @benoit74 and the content team will take care of it. Thank you for the assessment!

**Comment by benoit74** [comment]
Nope, this is a Zimit 2 file
And yes, metadata are incorrect, this is among other things we have to test why it is still only in dev ^^
Anyway, glad you tested this and it worked well !

FYI, these are the test Zimit 2 files we have for now:
- https://dev.library.kiwix.org/viewer#100rabbits_en_2024-01 
- https://dev.library.kiwix.org/viewer#fas-military-medicine_en_2024-01 
- https://dev.library.kiwix.org/viewer#solar.lowtechmagazine.com_en_all_2024-01 
- https://dev.library.kiwix.org/viewer#developer.mozilla.org_en_all_2024-01
- https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2024-01 

The last one has a known issue: https://github.com/openzim/warc2zim/issues/149

And all of them have incorrect scraper (version is incorrect) and publisher (must be openZIM) metadata.

I'm closing this issue, because we will move these files in due time, and should you want to test these files on your own (much welcome) and you encounter a problem, please open a dedicated issue.

**Comment by Jaifroid** [comment]
Um, if it's Zimit 1, why does it have warc-headers (C/H(/ namespace)? See screenshot. H/ headers are not in zimit2 files, hence this must be a zimit1 file. @mgautierfr can you confirm that it should be impossible for a zimit2 file to have warc-headers and a C/A/ namespace?

![image](https://github.com/openzim/zim-requests/assets/4304337/ebdeb04a-b2fe-4395-b85b-59d0773af9af)

**Comment by Jaifroid** [comment]
Also @benoit74, take a look at the detailed information about this file displayed in Kiwix JS (look at circled info in console log). Certainly no zimit2 file should have such MIME types or starting page in the C/A pseudo namespace.

![image](https://github.com/openzim/zim-requests/assets/4304337/24f441e5-bb6d-47b6-af38-d9bb53db6f2a)

**Comment by Jaifroid** [comment]
Final bit of evidence is that this file errors out in Kiwix Desktop, which is classic behaviour for zimit1:

![image](https://github.com/openzim/zim-requests/assets/4304337/5e134e8e-1cce-44b9-bcc2-c274f338f6b8)

**Comment by benoit74** [comment]
This should have been a U

**Comment by benoit74** [comment]
@rgaudin what is the process to move a ZIM manually to prod? I think I never did it, I've only uploaded ZIM to dev manually. Is it sufficient (for now, since CMS is like it is) to move the file?

**Comment by rgaudin** [comment]
If it can be redone by farm in a reasonable time, it should.
If it can't or not wanted (expecting low quality zim) a move is sufficient for now but as you guessed, it means the cms is not informed of this zim's existence

**Comment by Jaifroid** [comment]
Thanks, both. I would rate this as a high-quality scrape from my testing of it, which was the reason for requesting the move (because it's the first high-quality scrape, I think, for nearly a year). Of course it could be redone with a target of the production server and fingers crossed it's as good as this one!

**Comment by Jaifroid** [comment]
By the way @benoit74 not sure if you're aware that at least `fas-military-medicine_en_2024-01.zim` (in dev) is also zimit2, and I suspect a number of others. This ZIM in particular is good for testing PDF support with the Chromium sandbox.

**Comment by benoit74** [comment]
> By the way @benoit74 not sure if you're aware that at least fas-military-medicine_en_2024-01.zim (in dev) is also zimit2, and I suspect a number of others. This ZIM in particular is good for testing PDF support with the Chromium sandbox.

Yes, I'm the one who requested all of them, the full list is here: https://github.com/openzim/zim-requests/issues/791#issuecomment-1907587891 (except you should remove MDN from the list since as you spotted it has not been done with zimit2 by mistake)

> If it can be redone by farm in a reasonable time, it should.

It takes 20 hours, and it looks like we experienced issues in the past, so I'm not totally convinced this is the way to go

> If it can't or not wanted (expecting low quality zim) a move is sufficient for now but as you guessed, it means the cms is not informed of this zim's existence

Is there any plan to include a "move" feature in the Zimfarm? (I did not find an issue) I think it would be beneficial in terms of simplicity + quality (when the scraping is complex, it could be a strategy to always publish to dev, check quality, and then move file to prod, without redoing a scrape)

**Comment by Popolechien** [comment]
> Is there any plan to include a "move" feature in the Zimfarm?

Holy crap this is a great idea. I don't recall we've ever discussed it. I'll open a ticket.

**Comment by Jaifroid** [comment]
> It takes 20 hours, and it looks like we experienced issues in the past, so I'm not totally convinced this is the way to go

Good point. In that case, maybe we can simply uploaded it to the zimit directory in master.download.kiwix.org. Would it be picked up by library.kiwix.org automatically? I'd be happy to upload it if you like, as I expect any ticket to add a move feature would be completed long after this ZIM is no longer relevant! But I don't want to interfere, so just say the word.

**Comment by benoit74** [comment]
I just moved the file, it will appear in library.kiwix.org (and be removed from dev.library.kiwix.org) at next library refresh (in at most 1h): https://download.kiwix.org/zim/zimit/developer.mozilla.org_en_all_2024-01.zim

I relaunch the recipe with zimit2 this time (i.e. next time you see developer.mozilla.org_en_all_2024-01.zim in dev.library.kiwix.org, it will be a zimit2 file)
