### ISSUE TITLE
zim of GlobalNames 

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#8]
_From @amirh123123 on August 26, 2018 15:40_

this address 
http://globalnames.org/

_Copied from original issue: openzim/mwoffliner#364_

**Comment by RavanJAltaie** [comment]
Requested
https://farm.openzim.org/recipes/globalnames.org

**Comment by RavanJAltaie** [comment]
Succeeded.

**Comment by benoit74** [comment]
ZIM is not published on PROD and DEV version is mostly not working.

I disabled the recipe for now (https://farm.openzim.org/recipes/globalnames.org_en) since it needs to be fixed anyway.

Both core of the question is: what do we want to archive in the this ZIM?

1. The applications (web services) which helps people to register, find, index, check and organize biological scientific names and interconnect on-line information about species? This is not going to work, since they are web services we cannot archive them with Zimit. Scraper needed at least, but this is not going to be a simple one at all.

2. The PDF documents (at "Papers") and the documentation (at "Docs")? this could work, but we need a custom CSS to hide everything else. And I'm pretty sure it would be pretty deceptive to most users.

**Comment by Popolechien** [comment]
Yeah I agree there's low value here. Let's close this and focus on lower-hanging fruits.
