### ISSUE TITLE
zim demo

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#87]
_From @amirh123123 on March 28, 2018 17:27_

hi please make zim demo of files example i dont wikipedia i want download 10 articles in zim format wikipedia demo thanks

_Copied from original issue: openzim/mwoffliner#261_

**Comment by kelson42** [comment]
What would be the purpose of this demonstration ZIM file?

**Comment by kelson42** [comment]
_From @amirh123123 on March 28, 2018 18:18_


We understand the content of a large Zim file

**Comment by kelson42** [comment]
We provide already large ZIM files! What would be the purpose of this new demo file?

**Comment by kelson42** [comment]
_From @Popolechien on March 29, 2018 6:14_

I think there would be some value in having something more explicit than the Ray Charles zim file (if only because most people now do not know who he is). Could we instead automatically generate a small, monthly zim with the top 100 most read articles (like, literally, the weekly top100 from Hatnote https://top.hatnote.com/about.html)?

**Comment by kelson42** [comment]
@Popolechien This is a TOP selection you are talking about. I do not see any relation to a "demonstration" concept?!

**Comment by kelson42** [comment]
_From @amirh123123 on March 29, 2018 14:57_

exammple wikipedia computer i dont what i want download 10 articles of wikipedia computer in small zim file

**Comment by kelson42** [comment]
_From @Popolechien on March 29, 2018 15:0_

@kelson42 This would be much smaller than a TOP selection (10-100 articles) and would simply replace the current Ray Charles demo. But I think OP here is asking for some sort of preview feature, as in "what kind of articles can I find on a given subject".

**Comment by kelson42** [comment]
@amirh123123 @Popolechien To me, we should provide a link to http://library.kiwix.org/XXX so people can make an opinion about the content they want to download. This is something we should integrate to the library in Kiwix ports. But I'm quite against creating "demo" version for each ZIM file we produce.

**Comment by kelson42** [comment]
_From @Popolechien on April 3, 2018 9:41_

I don't think a demo version of each zim file is manageable. But the current demo (Ray Charles) has very little added value (except as proof-of-concept): a very small zim file automatically generated on a weekly basis and based on top views could be useful if it were packaged along with Kiwix (but that's a longer shot).

**Comment by kelson42** [comment]
_From @Jaifroid on September 17, 2018 20:54_

Sorry to revive an old issue, but I like @Popolechien's idea here. Ray Charles is getting long in the tooth. It is useful for developers only (for standardized testing, and devs could continue to use it), but not very meaningful for end-users of the Kiwix app unless they happen to be Jazz fans. Plain (non-packaged) versions of the Kiwix app would be more enticing if they had a demo ZIM with the kind of more universally "popular" content @Popolechien suggests.

**Comment by kelson42** [comment]
We have meanwhile a lot of small files... not sure this ticket is pertinent anymore.

**Comment by Popolechien** [comment]
Probably not, but we should make sure that Ray Charles is not the default suggestion (I think it was on android but can't see him now). If that's settled, then yes let's close the ticket.

**Comment by Jaifroid** [comment]
What I'm really missing is a "top 100" Wikipedia *without* video. We once did a top 100 *with* video that was 82MB (`wikipedia_en_100_2019-01.zim`). Without video it would have been a perfect demo file to distribute with the basic app. Purpose of a demo is to show off the features of the app and the kind of material available, so that the user will invest the time and bandwidth to download a fuller version.

The current `top_maxi` Wikipedia English file is a bit useless (at least for such purposes) IMHO. It is far too big for general distribution (6GB), but has far too few articles to be anything other than a bit frustrating for a user if they do invest quite a bit of time downloading it. So who is it pitched at? It could be useful for a thumb-drive demo, but not for online distribution.

In the meantime, I think the climate change ZIM is the nearest thing we have to a good, general-interest and informative (English-language) "replacement" for Ray Charles, albeit 10x bigger. Again, inclusion of video bloats it. I think we need a size between maxi and nopic that still has images and full text of articles but no massive videos...

**Comment by kelson42** [comment]
@Jaifroid I think you are talking about #160
