### ISSUE TITLE
Ted animation file 

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#874]
Hi, as per the screenshot below, I've noticed one video is not opening properly, others a re working fine in the same file.
What do you think?
<img width="539" alt="image" src="https://github.com/openzim/zim-requests/assets/116940574/02f5c1aa-4a3c-4338-bc7f-b0583a9235e4">

**Comment by benoit74** [comment]
Recipe: https://farm.openzim.org/recipes/ted_topic_animation

Upstream issue fixed, not yet released so I updated the recipe to use `dev` tag temporarily and confirm ZIM is OK. I requested the recipe.

**Comment by benoit74** [comment]
FYI, in the new ZIM the faulty video is not present anymore, the scraper did not achieved to download it.

**Comment by Popolechien** [comment]
I read this as a good thing, but you write as if it were a bad one?

**Comment by benoit74** [comment]
The fact that we do not have faulty videos in the ZIM is a good thing. 

I hoped the scraper would have be able to download it by a fallback to Youtube but code did not worked as expected, and this is a bad thing (see https://github.com/openzim/ted/issues/169 for details). We can however live with it for weeks or months, since this situation is way better than it has never been for months or maybe even years.
