### ISSUE TITLE
TED double namings

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#875]
Some of the resulted files for Ted by topic project have the word ted doubled
I checked the naming in the recipe, it looks fine
<img width="848" alt="image" src="https://github.com/openzim/zim-requests/assets/116940574/b819560e-c996-4e41-9e4e-bf1620a82587">

While other files are named correctly as below
<img width="857" alt="image" src="https://github.com/openzim/zim-requests/assets/116940574/0c5d4e25-5d8b-4008-b5f5-cc8d120d8306">

how can we fix that?

**Comment by benoit74** [comment]
Simply update the title and description in the corresponding recipe, e.g. https://farm.openzim.org/recipes/ted_topic_ted-conference/config

You need to find a title and a description which suits your requirement and clearly indicate that ted_mul_ted_conference for instance is a ZIM containing all official TED conferences, while ted_mul_tedx contains all TEDx conferences, etc ...

**Comment by RavanJAltaie** [comment]
I've reviewed the content of the mentioned files and the naming of all of them is corresponding to the content in a suitable way.

**Comment by benoit74** [comment]
Did you mean that you've updated some titles to make them less confusing? I've checked few recipes and the word "ted" is still doubled in title, looks like you did not updated anything. I find this confusing, you've found this confusing, there is a significant probability that many other folks will find it confusing as well.

**Comment by benoit74** [comment]
Any news to share?

**Comment by benoit74** [comment]
Up? (I reopen since it seems the issue is not addressed)

**Comment by benoit74** [comment]
Discussed live again with Ravan and Stephane, Ravan considers it makes more sense to keep the double "TED" even in titles because it is clearer.

Now that we've discussed it, I tend to also believe it will help to avoid collision between for instance "TED books", a ZIM of conference about books (where books is the topic), and "TED ted books", a ZIM about companion talks on books published by TED (where ted books is the topic). This collision might not exists yet but could come up in the future.
