### ISSUE TITLE
openstreet map wiki

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#91]
_From @kelson42 on July 9, 2017 15:25_

Add support for OpenStreetMap Wiki (https://wiki.openstreetmap.org/wiki/)

_Copied from original issue: openzim/mwoffliner#94_

**Comment by chjohn22** [comment]
Website URL: https://wiki.openstreetmap.org/wiki/Main_Page
    License: Creative Commons Attribution-ShareAlike 2.0 license 
    Desired ZIM Title: OpenStreetMap Wiki
    Desired ZIM Description: The official wiki of OpenStreetMap
    Desired ZIM Icon –png (URL or attach one): https://commons.wikimedia.org/wiki/File:Openstreetmap_logo.svg
    Language (ISO 639-3): eng
    Desired Main Page (homepage): https://wiki.openstreetmap.org/wiki/Main_Page
    Is this a MediaWiki?: yes
    Articles List URL (mediawiki): https://wiki.openstreetmap.org/wiki/Special:AllPages

**Comment by kelson42** [comment]
Recipe https://farm.openzim.org/recipes/osm-wiki

**Comment by Popolechien** [comment]
The recipe failed the last three times it ran. 
@kelson42 any idea?

**Comment by Coloradohusky** [comment]
Fails seem to be due to the Visual Editor (`apierror-visualeditor-docserver-http-error`), which is also referenced [here](https://github.com/openzim/mwoffliner/issues/1623) as causing a lot of issues. Looks like a pull request is underway, but still under review, so hopefully once it goes through it will fix the problems with this download.

**Comment by kelson42** [comment]
Thx for your patience
