### ISSUE TITLE
Weird number of article counts accross wikipedia flavors

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#985]
Someone reported an issue on reddit: "why are all the article counts different? I thought the only difference was how detailed the articles are. "

https://www.reddit.com/r/Kiwix/comments/1cgbib2/why_are_all_the_article_counts_different_i/

![image](https://github.com/openzim/zim-requests/assets/7102089/b07b3499-45d3-4690-915c-da8b5029d97a)

@mgautierfr @kelson42 @rgaudin I don't know who should have a look into it ; maybe one of you already have the explanation

**Comment by kelson42** [comment]
@benoit74 Pretty sure this is a bug, probably at the reader side. But should be checked.

**Comment by rgaudin** [comment]
I think I know what's going on ; I'll check

**Comment by rgaudin** [comment]
There are two issues here:

- `nopic` was apparently buggy and recreated a few days later in February.
- `mini` numbers are wrong because of a bug in Kiwix Apple reader that has been fixed.

<img width="718" alt="Screenshot 2024-05-01 at 16 20 54" src="https://github.com/openzim/zim-requests/assets/57929/8d4d1830-e29f-4e0c-8f12-1c94a54ef59d">


Looks consistent now with nightly build ; here what I get for a few major languages.

<img width="762" alt="Screenshot 2024-05-01 at 16 04 27" src="https://github.com/openzim/zim-requests/assets/57929/652274ec-0a2b-443c-aebb-3bafff9ae3c4">
<img width="745" alt="Screenshot 2024-05-01 at 16 08 02" src="https://github.com/openzim/zim-requests/assets/57929/1ce6a6e8-0a7c-49fa-aeaf-968ba7f551ef">
<img width="762" alt="Screenshot 2024-05-01 at 16 07 49" src="https://github.com/openzim/zim-requests/assets/57929/2e87546b-4e2f-4870-878b-7f1be94b7cae">
<img width="743" alt="Screenshot 2024-05-01 at 16 07 38" src="https://github.com/openzim/zim-requests/assets/57929/bc48401c-28e1-4139-93bb-c15e07ac81c6">
